openapi: 3.0.1
info:
  title: E-Commerce API
  version: 1.0.0
  description: API Documentation for E-Commerce Platform
servers:
  - url: http://localhost:8080
paths:
  /balance/charge:
    post:
      summary: 결제에 사용될 금액을 충전
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                amount:
                  type: integer
      responses:
        '200':
          description: 충전 성공
  /balance/{userId}:
    get:
      summary: 사용자 장액 조회
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 장액 정보 반환
  /products:
    get:
      summary: 상품 조회
      responses:
        '200':
          description: 상품 목록 반환
  /coupons:
    post:
      summary: 선착순 쿠폰 발급
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
      responses:
        '200':
          description: 발급 성공
    get:
      summary: 사용자 쿠폰 목록 조회
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 쿠폰 목록 반환
  /orders:
    post:
      summary: 주문/결제 수행
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                couponId:
                  type: integer
                  nullable: true
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      productId:
                        type: integer
                      quantity:
                        type: integer
      responses:
        '200':
          description: 결제 성공 반환
  /products/popular:
    get:
      summary: 인기 상품 5개 조회
      responses:
        '200':
          description: 인기 상품 목록 반환